// Generated by CoffeeScript 1.12.3
(function() {
  var I;

  I = (function() {
    function I() {
      this.site = '#unknow';
      return;
    }

    I.prototype.init = function() {};

    I.prototype.get_info = function() {
      return {
        site: this.site,
        url: document.URL,
        title: $('title').text(),
        title_video: '#video_title',
        title_sub: '#sub_title',
        size: '#unknow_size',
        max_time_s: '#unknow_max_time_s'
      };
    };

    I.prototype.set_time = function(time_s) {};

    I.prototype.get_time = function() {
      return -1;
    };

    I.prototype.pause = function() {};

    return I;

  })();

  module.exports = I;

}).call(this);

//# sourceMappingURL=I.js.map
