// Generated by CoffeeScript 1.12.3
(function() {
  var I, log, m_vqq,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  log = require('../log');

  I = require('./I');

  m_vqq = (function(superClass) {
    extend(m_vqq, superClass);

    function m_vqq() {
      return m_vqq.__super__.constructor.apply(this, arguments);
    }

    m_vqq.prototype.init = function() {
      this.site = 'vqq';
      return log.c('c_m/vqq: init done. ');
    };

    m_vqq.prototype.get_info = function() {
      var o;
      o = m_vqq.__super__.get_info.call(this);
      return o;
    };

    m_vqq.prototype.get_time = function() {};

    m_vqq.prototype.set_time = function(time_s) {};

    m_vqq.prototype.pause = function() {};

    return m_vqq;

  })(I);

  module.exports = m_vqq;

}).call(this);

//# sourceMappingURL=vqq.js.map
