// Generated by CoffeeScript 1.12.3
(function() {
  var I, log, m_youku,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  log = require('../log');

  I = require('./I');

  m_youku = (function(superClass) {
    extend(m_youku, superClass);

    function m_youku() {
      return m_youku.__super__.constructor.apply(this, arguments);
    }

    m_youku.prototype.init = function() {
      this.site = 'youku';
      return log.c('c_m/youku: init done. ');
    };

    m_youku.prototype.get_info = function() {
      var o;
      o = m_youku.__super__.get_info.call(this);
      return o;
    };

    m_youku.prototype.get_time = function() {};

    m_youku.prototype.set_time = function(time_s) {};

    m_youku.prototype.pause = function() {};

    return m_youku;

  })(I);

  module.exports = m_youku;

}).call(this);

//# sourceMappingURL=youku.js.map
