# merge.bat.coffee, parse_v-crx/src/s/p_dl/

config = require '../config'


make_ffmpeg_merge_sh = (file_list, output_file, sh_filename) ->
  output = []
  o = (line) ->
    output.push line
  
  o '@echo on'
  o 'chcp 65001'
  o ''
  
  ffmpeg = config.merge_ffmpeg_bin
  o "#{ffmpeg} -i \"concat:#{file_list.join('|')}\" -c copy #{output_file}"
  o ''
  o 'pause'
  o 'cmd'
  
  o ''
  o ":: end #{sh_filename}: ffmpeg merge bat, generated by parse_v-crx at #{new Date()}"
  o ''
  # output
  output.join('\r\n') + '\r\n'

module.exports = make_ffmpeg_merge_sh
# end merge.bat.coffee

