// Generated by CoffeeScript 1.12.3
(function() {
  var I;

  I = (function() {
    function I(raw) {
      this.url = raw.url;
      this.site = raw.site;
      this._title = raw.title;
      this._info = null;
      return;
    }

    I.prototype.init = function() {};

    I.prototype.set_info = function(info) {
      this._info = info;
    };

    I.prototype.on_request = function(info) {};

    I.prototype.cleanup = function() {};

    I.prototype.get_info = function() {
      var o;
      if (this._info === null) {
        return {
          site: this.site,
          url: this.url,
          title: this._title,
          playing: false
        };
      }
      o = {
        playing: true,
        site: this._info.site,
        url: this._info.url,
        title: this._info.title,
        title_video: this._info.title_video,
        title_sub: this._info.title_sub,
        size: this._info.size,
        max_time_s: this._info.max_time_s,
        video: {}
      };
      o.video[this._info.size] = {
        size: this._info.size,
        file: []
      };
      return o;
    };

    I.prototype.get_url = function(raw) {
      return raw;
    };

    I.prototype._make_filename = function(i, i_max, time_s) {
      var m, main;
      m = Math.round(time_s / 60);
      main = this._info.title_video + "_" + this._info.title_sub + "_" + this._info.size + "_" + this._info.site + "_.part." + m + "min." + i + ".of." + i_max;
      return main.split(' ').join('-');
    };

    return I;

  })();

  module.exports = I;

}).call(this);

//# sourceMappingURL=I.js.map
